To create the archive do:

If `pkg-config --modversion libxul` >= 2*

make -f xul_2.mak

If `pkg-config --modversion libxul` < 2

make -f xul_1.mak


Then install the XPI archive in Firefox and enjoy. The xpi is at ../build ($ROOTDIR/build)
